version: '3.7'

services:
    web:
        build: .
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DATABASE_URL: postgres://postgres:password@db:5432/example
        depends_on: 
            - db
        volumes:
            - "${PWD}:/usr/src/app"
        networks:
            - mynetwork
    
    db:
        image: postgres:12
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: example
        ports:
            - 5432:5432
        networks:
            - mynetwork
            
networks:
    mynetwork:
